// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: gateway2app.proto

/*
Package external is a generated protocol buffer package.

It is generated from these files:
	gateway2app.proto

It has these top-level messages:
	LoginReq
	IndexReq
	UserInfo
	LoginRes
	RegisterReq
	ReturnRes
	QianxunReq
	TokenReq
	TelReq
	TokenRes
	RankingInfoRes
	AppListRes
*/
package external

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserServceRpc service

type UserServceRpcClient interface {
	Login(ctx context.Context, in *LoginReq, opts ...client.CallOption) (*LoginRes, error)
	Register(ctx context.Context, in *RegisterReq, opts ...client.CallOption) (*ReturnRes, error)
	ModifyPwdByTel(ctx context.Context, in *LoginReq, opts ...client.CallOption) (*ReturnRes, error)
	AddQianXunCode(ctx context.Context, in *QianxunReq, opts ...client.CallOption) (*ReturnRes, error)
	QianXunSnsVerify(ctx context.Context, in *QianxunReq, opts ...client.CallOption) (*ReturnRes, error)
	SetUserToken(ctx context.Context, in *TokenReq, opts ...client.CallOption) (*ReturnRes, error)
	GetUserToken(ctx context.Context, in *TelReq, opts ...client.CallOption) (*TokenRes, error)
	GetUserRankingInfo(ctx context.Context, in *TelReq, opts ...client.CallOption) (*RankingInfoRes, error)
	AppList(ctx context.Context, in *IndexReq, opts ...client.CallOption) (*AppListRes, error)
}

type userServceRpcClient struct {
	c           client.Client
	serviceName string
}

func NewUserServceRpcClient(serviceName string, c client.Client) UserServceRpcClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "external"
	}
	return &userServceRpcClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *userServceRpcClient) Login(ctx context.Context, in *LoginReq, opts ...client.CallOption) (*LoginRes, error) {
	req := c.c.NewRequest(c.serviceName, "UserServceRpc.Login", in)
	out := new(LoginRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServceRpcClient) Register(ctx context.Context, in *RegisterReq, opts ...client.CallOption) (*ReturnRes, error) {
	req := c.c.NewRequest(c.serviceName, "UserServceRpc.Register", in)
	out := new(ReturnRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServceRpcClient) ModifyPwdByTel(ctx context.Context, in *LoginReq, opts ...client.CallOption) (*ReturnRes, error) {
	req := c.c.NewRequest(c.serviceName, "UserServceRpc.ModifyPwdByTel", in)
	out := new(ReturnRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServceRpcClient) AddQianXunCode(ctx context.Context, in *QianxunReq, opts ...client.CallOption) (*ReturnRes, error) {
	req := c.c.NewRequest(c.serviceName, "UserServceRpc.AddQianXunCode", in)
	out := new(ReturnRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServceRpcClient) QianXunSnsVerify(ctx context.Context, in *QianxunReq, opts ...client.CallOption) (*ReturnRes, error) {
	req := c.c.NewRequest(c.serviceName, "UserServceRpc.QianXunSnsVerify", in)
	out := new(ReturnRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServceRpcClient) SetUserToken(ctx context.Context, in *TokenReq, opts ...client.CallOption) (*ReturnRes, error) {
	req := c.c.NewRequest(c.serviceName, "UserServceRpc.SetUserToken", in)
	out := new(ReturnRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServceRpcClient) GetUserToken(ctx context.Context, in *TelReq, opts ...client.CallOption) (*TokenRes, error) {
	req := c.c.NewRequest(c.serviceName, "UserServceRpc.GetUserToken", in)
	out := new(TokenRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServceRpcClient) GetUserRankingInfo(ctx context.Context, in *TelReq, opts ...client.CallOption) (*RankingInfoRes, error) {
	req := c.c.NewRequest(c.serviceName, "UserServceRpc.GetUserRankingInfo", in)
	out := new(RankingInfoRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServceRpcClient) AppList(ctx context.Context, in *IndexReq, opts ...client.CallOption) (*AppListRes, error) {
	req := c.c.NewRequest(c.serviceName, "UserServceRpc.AppList", in)
	out := new(AppListRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserServceRpc service

type UserServceRpcHandler interface {
	Login(context.Context, *LoginReq, *LoginRes) error
	Register(context.Context, *RegisterReq, *ReturnRes) error
	ModifyPwdByTel(context.Context, *LoginReq, *ReturnRes) error
	AddQianXunCode(context.Context, *QianxunReq, *ReturnRes) error
	QianXunSnsVerify(context.Context, *QianxunReq, *ReturnRes) error
	SetUserToken(context.Context, *TokenReq, *ReturnRes) error
	GetUserToken(context.Context, *TelReq, *TokenRes) error
	GetUserRankingInfo(context.Context, *TelReq, *RankingInfoRes) error
	AppList(context.Context, *IndexReq, *AppListRes) error
}

func RegisterUserServceRpcHandler(s server.Server, hdlr UserServceRpcHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&UserServceRpc{hdlr}, opts...))
}

type UserServceRpc struct {
	UserServceRpcHandler
}

func (h *UserServceRpc) Login(ctx context.Context, in *LoginReq, out *LoginRes) error {
	return h.UserServceRpcHandler.Login(ctx, in, out)
}

func (h *UserServceRpc) Register(ctx context.Context, in *RegisterReq, out *ReturnRes) error {
	return h.UserServceRpcHandler.Register(ctx, in, out)
}

func (h *UserServceRpc) ModifyPwdByTel(ctx context.Context, in *LoginReq, out *ReturnRes) error {
	return h.UserServceRpcHandler.ModifyPwdByTel(ctx, in, out)
}

func (h *UserServceRpc) AddQianXunCode(ctx context.Context, in *QianxunReq, out *ReturnRes) error {
	return h.UserServceRpcHandler.AddQianXunCode(ctx, in, out)
}

func (h *UserServceRpc) QianXunSnsVerify(ctx context.Context, in *QianxunReq, out *ReturnRes) error {
	return h.UserServceRpcHandler.QianXunSnsVerify(ctx, in, out)
}

func (h *UserServceRpc) SetUserToken(ctx context.Context, in *TokenReq, out *ReturnRes) error {
	return h.UserServceRpcHandler.SetUserToken(ctx, in, out)
}

func (h *UserServceRpc) GetUserToken(ctx context.Context, in *TelReq, out *TokenRes) error {
	return h.UserServceRpcHandler.GetUserToken(ctx, in, out)
}

func (h *UserServceRpc) GetUserRankingInfo(ctx context.Context, in *TelReq, out *RankingInfoRes) error {
	return h.UserServceRpcHandler.GetUserRankingInfo(ctx, in, out)
}

func (h *UserServceRpc) AppList(ctx context.Context, in *IndexReq, out *AppListRes) error {
	return h.UserServceRpcHandler.AppList(ctx, in, out)
}
